import Foundation

/// The access level of code generated by ``UserDefaultDataStore(using:accessLevel:)``.
public enum AccessLevel: String {
    case `public`
    case `private`
    case `internal`
    case `fileprivate`
    case `open`
}
